"""Configuration settings and constants for the Meal Planner application."""

from pathlib import Path

DB_FILENAME = "meal_planner.db"
CONTAINER_DATA_DIR = Path("/root/data")
CONTAINER_DB_FULL_PATH = CONTAINER_DATA_DIR / DB_FILENAME
CONTAINER_MAIN_DATABASE_URL = f"sqlite:///{CONTAINER_DB_FULL_PATH}"

APP_ROOT_IN_CONTAINER = Path("/root")
ALEMBIC_INI_FILENAME = "alembic.ini"
ALEMBIC_DIR_NAME = "alembic"
ALEMBIC_INI_PATH_IN_CONTAINER = APP_ROOT_IN_CONTAINER / ALEMBIC_INI_FILENAME
ALEMBIC_DIR_PATH_IN_CONTAINER = APP_ROOT_IN_CONTAINER / ALEMBIC_DIR_NAME
