repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
        stages: [pre-push]
    -   id: check-toml
        stages: [pre-push]
-   repo: local
    hooks:
    -   id: ruff-check
        name: Run ruff check
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
    -   id: ruff-format
        name: Check ruff format
        entry: uv run ruff format --check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
    -   id: pyright
        name: Run pyright type checker
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
    -   id: pytest
        name: Check tests and test coverage
        entry: uv run ./run_fast_coverage.sh
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
