repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
        stages: [pre-push]
    -   id: check-toml
        stages: [pre-push]
-   repo: local
    hooks:
    -   id: ruff-lint
        name: Run ruff lint
        entry: uv run ruff lint
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
    -   id: ruff-format
        name: Check ruff format
        entry: uv run ruff format --check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
    -   id: pyright
        name: Run pyright type checker
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
    -   id: pytest
        name: Run tests and check coverage
        entry: uv run pytest -vv --cov=meal_planner --runslow --cov-fail-under=100
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
